# -*- coding: utf-8 -*-
"""start.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q4eCECgFoCJWr3Bzlt1QoHNXs-T1Q9np
"""

import json
from collections import Counter
import pandas as pd

# -------------------------------
# 1. Load dataset
# -------------------------------
file_path = "/content/decompose_dataset.json"   # change path if needed

with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

print("Total samples:", len(data))


# -------------------------------
# 2. Inspect first few samples
# -------------------------------
for i, item in enumerate(data[:3]):
    print(f"\n--- SAMPLE {i+1} ---")
    print("ID:", item.get("id"))
    print("Complex Question:", item.get("complex_question"))
    print("Question Type:", item.get("question_type"))
    print("Source Articles:", item.get("source_articles"))
    print("Num Sub Questions:", item.get("num_sub_questions"))
    print("Sub Questions:")

    for sq in item.get("sub_questions", []):
        print(f"  {sq['id']}. {sq['question']}  | type={sq['type']} | depends_on={sq['depends_on']}")

# -------------------------------
# 3. Dataset summary
# -------------------------------
question_type_counts = Counter(item["question_type"] for item in data)
num_subq_counts = Counter(item["num_sub_questions"] for item in data)

print("\nQuestion Type Distribution:")
for k, v in question_type_counts.items():
    print(f"{k}: {v}")

print("\nSub-question Count Distribution:")
for k, v in sorted(num_subq_counts.items()):
    print(f"{k} sub-questions: {v}")

# -------------------------------
# 4. Convert to dataframe
# -------------------------------
rows = []

for item in data:
    sub_questions = [sq["question"] for sq in item.get("sub_questions", [])]
    sub_types = [sq["type"] for sq in item.get("sub_questions", [])]

    rows.append({
        "id": item.get("id"),
        "complex_question": item.get("complex_question"),
        "question_type": item.get("question_type"),
        "num_sub_questions": item.get("num_sub_questions"),
        "source_articles": ", ".join(item.get("source_articles", [])),
        "sub_questions_joined": " || ".join(sub_questions),
        "sub_types_joined": " || ".join(sub_types)
    })

df = pd.DataFrame(rows)

print("\nDataFrame shape:", df.shape)
print(df.head(5))

# -------------------------------
# 5. Helper function to inspect one sample
# -------------------------------
def show_sample(index):
    item = data[index]
    print("\n====================================")
    print("ID:", item["id"])
    print("QUESTION:", item["complex_question"])
    print("TYPE:", item["question_type"])
    print("SOURCE ARTICLES:", item["source_articles"])
    print("SUB-QUESTIONS:")
    for sq in item["sub_questions"]:
        print(f"  {sq['id']}. {sq['question']}")
        print(f"     type={sq['type']}, depends_on={sq['depends_on']}")
    print("====================================")

# Example
show_sample(0)
show_sample(5)

# -------------------------------
# 6. Prepare training pairs
# -------------------------------
train_pairs = []

for item in data:
    input_text = item["complex_question"]
    output_text = " || ".join([sq["question"] for sq in item["sub_questions"]])

    train_pairs.append({
        "input_text": input_text,
        "target_text": output_text,
        "question_type": item["question_type"]
    })

train_df = pd.DataFrame(train_pairs)

print("\nTraining pairs created:", len(train_df))
print(train_df.head(3))

# -------------------------------
# 7. Check last sub-question pattern
# -------------------------------
for i in range(5):
    item = data[i]
    last_sq = item["sub_questions"][-1]
    print(f"\nSample {item['id']}")
    print("Question Type:", item["question_type"])
    print("Last Sub-question:", last_sq["question"])
    print("Last Sub-question Type:", last_sq["type"])

""" # Build a baseline decomposer"""

# --------------------------------
# 8. Inspect patterns by question type
# --------------------------------
from collections import defaultdict

type_examples = defaultdict(list)

for item in data:
    qtype = item["question_type"]
    if len(type_examples[qtype]) < 3:
        type_examples[qtype].append(item)

for qtype, examples in type_examples.items():
    print(f"\n========== {qtype.upper()} ==========")
    for ex in examples:
        print("\nComplex Question:", ex["complex_question"])
        for sq in ex["sub_questions"]:
            print(" -", sq["question"], f"[{sq['type']}]")

import re

def extract_articles(question):
    """
    Extract all article references from a question.
    Handles:
    - Article 14
    - Article 16(2)
    - Articles 14 and 16(2)
    - Articles 221, 222, and 223
    """
    pattern = r'Article[s]?\s+((?:\d+[A-Z]?(?:\([^)]+\))?)(?:\s*(?:,|and)\s*\d+[A-Z]?(?:\([^)]+\))?)*)'

    matches = re.findall(pattern, question, flags=re.IGNORECASE)

    articles = []
    for match in matches:
        nums = re.findall(r'\d+[A-Z]?(?:\([^)]+\))?', match)
        articles.extend(nums)

    return articles

tests = [
    "How do Articles 14 and 16(2) together ensure fairness in public employment?",
    "How do Articles 221, 222, and 223 address different aspects of service conditions?",
    "What does Article 243K(2) say?",
    "How do Articles 39, 40 and 41 relate?"
]

for t in tests:
    print("\nQuestion:", t)
    print("Extracted:", extract_articles(t))

def infer_question_type(question):
    q = question.lower()

    if any(word in q for word in ["difference", "compare", "differ", "distinction", "versus", "as opposed to"]):
        return "comparative"

    if any(word in q for word in ["if", "when", "in the absence", "what happens", "under what condition", "unless"]):
        return "conditional"

    return "analytical"

questions = [
    "How does the duration of the Council of States differ from the duration of the House of the People?",
    "If a person acquires foreign citizenship, what happens to Indian citizenship?",
    "How do the provisions of Article 14 and Article 16(2) together ensure fairness in public employment?"
]

for q in questions:
    print(q)
    print("Predicted type:", infer_question_type(q))
    print()

import re

STOPWORDS = {
    "how", "does", "do", "is", "are", "the", "of", "and", "or", "to", "in", "for",
    "what", "when", "if", "a", "an", "their", "they", "together", "under", "with",
    "from", "by", "on", "at", "this", "that", "these", "those", "it", "as"
}

LEGAL_PHRASE_PATTERNS = [
    r"Council of States",
    r"House of the People",
    r"public employment",
    r"Indian citizenship",
    r"foreign State",
    r"foreign citizenship",
    r"High Court",
    r"Supreme Court",
    r"Legislative Assembly",
    r"Legislative Council",
    r"State Election Commissioner",
    r"Comptroller and Auditor-General",
    r"Chief Justice of India",
    r"Fundamental Rights",
    r"village panchayats",
    r"secretarial staff",
    r"Consolidated Fund of a State",
    r"Governor",
    r"President",
    r"Speaker",
    r"Deputy Speaker"
]

def extract_key_phrases_v2(question):
    q = question.strip()
    q_lower = q.lower()

    found_phrases = []

    # 1. Match known legal phrases first
    for pattern in LEGAL_PHRASE_PATTERNS:
        if re.search(pattern, q, flags=re.IGNORECASE):
            found_phrases.append(pattern)

    # 2. Add domain keywords manually if present
    domain_keywords = [
        "duration", "citizenship", "equality", "discrimination",
        "fairness", "absence", "presiding officer", "executive power",
        "appointment", "tenure", "removal", "oath", "rule-making powers"
    ]

    for kw in domain_keywords:
        if kw.lower() in q_lower and kw not in found_phrases:
            found_phrases.append(kw)

    # 3. Fallback: capture capitalized multi-word phrases
    cap_phrases = re.findall(r'(?:[A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)', q)
    for cp in cap_phrases:
        if cp not in found_phrases:
            found_phrases.append(cp)

    # 4. Final fallback: meaningful non-stopword tokens
    if not found_phrases:
        words = re.findall(r'\b[a-zA-Z]{4,}\b', q_lower)
        filtered = [w for w in words if w not in STOPWORDS]
        found_phrases.extend(list(dict.fromkeys(filtered[:3])))

    return found_phrases[:4]

test_questions = [
    "How does the duration of the Council of States differ from the duration of the House of the People?",
    "If a person voluntarily acquires the citizenship of a foreign State, what happens to their Indian citizenship?",
    "What happens if the Speaker is absent from a sitting?",
    "How is fairness in public employment protected?"
]

for q in test_questions:
    print("\nQuestion:", q)
    print("Concepts:", extract_key_phrases_v2(q))

"""# Baseline decomposition logic"""

def baseline_decompose_v3(question, question_type=None):
    if question_type is None:
        question_type = infer_question_type(question)

    articles = extract_articles(question)
    concepts = extract_key_phrases_v2(question)
    sub_questions = []

    if question_type == "comparative":
        if len(articles) >= 2:
            sub_questions.append(f"What does Article {articles[0]} provide?")
            sub_questions.append(f"What does Article {articles[1]} provide?")
            sub_questions.append(
                f"How do Article {articles[0]} and Article {articles[1]} differ or relate in the context of the question?"
            )
        elif len(concepts) >= 2:
            sub_questions.append(f"What is the constitutional meaning or scope of {concepts[0]}?")
            sub_questions.append(f"What is the constitutional meaning or scope of {concepts[1]}?")
            sub_questions.append(
                f"How do {concepts[0]} and {concepts[1]} differ or relate in the context of the question?"
            )
        else:
            sub_questions.append("What is the first legal concept involved in the question?")
            sub_questions.append("What is the second legal concept involved in the question?")
            sub_questions.append("How do these two legal concepts differ or relate?")

    elif question_type == "conditional":
        if len(articles) >= 1:
            sub_questions.append(f"What rule is stated in Article {articles[0]}?")
            sub_questions.append(f"What condition, exception, or event is relevant under Article {articles[0]}?")
            sub_questions.append(
                f"Based on Article {articles[0]}, what is the legal outcome when that condition occurs?"
            )
        elif len(concepts) >= 2:
            sub_questions.append(f"What legal rule governs {concepts[0]}?")
            sub_questions.append(f"What condition or triggering event involving {concepts[1]} is described in the question?")
            sub_questions.append("What is the legal or constitutional outcome when that condition occurs?")
        else:
            sub_questions.append("What legal rule applies to the situation described in the question?")
            sub_questions.append("What condition, exception, or triggering event is mentioned in the question?")
            sub_questions.append("What is the legal outcome when that condition occurs?")

    else:  # analytical
        if len(articles) >= 2:
            for art in articles[:3]:
                sub_questions.append(f"What does Article {art} provide?")
            sub_questions.append("How do these constitutional provisions work together to answer the original question?")
        elif len(concepts) >= 2:
            sub_questions.append(f"What constitutional principle governs {concepts[0]}?")
            sub_questions.append(f"What constitutional principle governs {concepts[1]}?")
            if len(concepts) >= 3:
                sub_questions.append(f"What is the role of {concepts[2]} in the constitutional context of the question?")
            sub_questions.append("How do these constitutional principles work together to answer the original question?")
        else:
            sub_questions.append("What is the first constitutional principle involved in this question?")
            sub_questions.append("What is the second constitutional principle involved in this question?")
            sub_questions.append("How do these legal principles work together to answer the question?")

    return {
        "question": question,
        "question_type": question_type,
        "articles_found": articles,
        "concepts_found": concepts,
        "sub_questions": sub_questions
    }

for q in test_questions:
    result = baseline_decompose_v3(q)
    print("\n====================================")
    print("Question:", result["question"])
    print("Type:", result["question_type"])
    print("Articles found:", result["articles_found"])
    print("Concepts found:", result["concepts_found"])
    print("Generated sub-questions:")
    for i, sq in enumerate(result["sub_questions"], 1):
        print(f"{i}. {sq}")

"""# generate sub-questions in dataset style"""

def detect_focus(question):
    q = question.lower()

    focus_keywords = [
        "duration",
        "citizenship",
        "fairness",
        "equality",
        "discrimination",
        "appointment",
        "removal",
        "oath",
        "tenure",
        "salary",
        "allowances",
        "power",
        "rule-making powers",
        "executive power",
        "secretarial staff",
        "presiding officer",
        "absence",
        "office",
        "conditions of service",
        "validity",
        "disqualification",
        "special address",
        "messages",
        "language",
        "rights",
        "duties",
        "procedure",
        "expenditure",
        "grants"
    ]

    for kw in sorted(focus_keywords, key=len, reverse=True):
        if kw in q:
            return kw

    # fallback
    return None

for q in [
    "How does the duration of the Council of States differ from the duration of the House of the People?",
    "If a person voluntarily acquires the citizenship of a foreign State, what happens to their Indian citizenship?",
    "How is fairness in public employment protected?"
]:
    print(q)
    print("Focus:", detect_focus(q))
    print()

def clean_text(text):
    text = re.sub(r'\s+', ' ', text).strip()

    # remove repeated ", fairness" or similar tail repeats
    text = re.sub(r',\s*([A-Za-z ]+)\s*,\s*\1$', r', \1', text, flags=re.IGNORECASE)

    # remove duplicate consecutive words
    words = text.split()
    cleaned = []
    for w in words:
        if not cleaned or cleaned[-1].lower() != w.lower():
            cleaned.append(w)

    text = " ".join(cleaned)

    # small cleanup for punctuation spacing
    text = re.sub(r'\s+([,?.])', r'\1', text)

    return text

ARTICLE_HINTS = {
    "14": "equality before the law",
    "15": "prohibition of discrimination",
    "16": "equality of opportunity in public employment",
    "16(2)": "prohibition of discrimination in public employment",
    "21": "protection of life and personal liberty",
    "83": "duration of Houses of Parliament",
    "67": "term of office of the Vice-President",
    "153": "Governor for each State",
    "180(2)": "presiding officer of Legislative Assembly in absence of Speaker and Deputy Speaker",
    "225": "rule-making powers of the High Court",
    "243K(2)": "conditions of service and tenure of the State Election Commissioner",
    "148(1)": "removal process of the Comptroller and Auditor-General",
    "148(2)": "oath requirement of the Comptroller and Auditor-General",
    "100(1)": "voting rights and casting vote in Parliament",
    "98": "secretarial staff of Parliament",
    "187(2)": "recruitment and conditions of service of secretarial staff of State Legislature",
    "9": "effect of acquiring foreign citizenship on Indian citizenship"
}

def get_article_hint(article):
    return ARTICLE_HINTS.get(article, None)

def dataset_style_decompose_v3(question, question_type=None):
    if question_type is None:
        question_type = infer_question_type(question)

    articles = extract_articles(question)
    concepts = extract_key_phrases_v2(question)
    focus = detect_focus(question)

    sub_questions = []

    # -------------------------------
    # COMPARATIVE
    # -------------------------------
    if question_type == "comparative":
        if len(articles) >= 2:
            if focus:
                sub_questions.append(f"What is the scope of {focus} under Article {articles[0]}?")
                sub_questions.append(f"What is the scope of {focus} under Article {articles[1]}?")
                sub_questions.append(
                    f"Based on their treatment of {focus}, how do Article {articles[0]} and Article {articles[1]} differ?"
                )
            else:
                sub_questions.append(f"What does Article {articles[0]} provide?")
                sub_questions.append(f"What does Article {articles[1]} provide?")
                sub_questions.append(
                    f"How do the provisions of Article {articles[0]} and Article {articles[1]} differ?"
                )

        elif len(concepts) >= 2:
            c1, c2 = concepts[0], concepts[1]

            if focus == "duration":
                sub_questions.append(f"What is the prescribed duration for the {c1}?")
                sub_questions.append(f"What is the prescribed duration for the {c2}?")
                sub_questions.append(
                    f"Based on their respective durations, what are the key differences between the {c1} and the {c2}?"
                )
            else:
                sub_questions.append(f"What is the constitutional position of {c1} in relation to {focus or 'the issue raised'}?")
                sub_questions.append(f"What is the constitutional position of {c2} in relation to {focus or 'the issue raised'}?")
                sub_questions.append(
                    f"How do {c1} and {c2} differ in the context of {focus or 'the original question'}?"
                )

    # -------------------------------
    # CONDITIONAL
    # -------------------------------
    elif question_type == "conditional":
        if len(articles) >= 1:
            art = articles[0]
            hint = get_article_hint(art)

            if hint:
                sub_questions.append(f"What does Article {art} state regarding {hint}?")
                sub_questions.append(f"What condition, exception, or event is relevant under Article {art}?")
                sub_questions.append(
                    f"Based on Article {art}, what happens when that condition or event occurs?"
                )
            elif focus:
                sub_questions.append(f"What does Article {art} state regarding {focus}?")
                sub_questions.append(f"What condition, exception, or event concerning {focus} is relevant under Article {art}?")
                sub_questions.append(
                    f"Based on Article {art}, what happens when that condition or event occurs?"
                )
            else:
                sub_questions.append(f"What rule is stated in Article {art}?")
                sub_questions.append(f"What condition or exception is relevant under Article {art}?")
                sub_questions.append(f"Based on Article {art}, what is the legal outcome when that condition occurs?")

        elif len(concepts) >= 2:
            c1 = concepts[0]
            c2 = concepts[1]

            if focus == "citizenship":
                sub_questions.append(f"What is the constitutional rule regarding {c1}?")
                sub_questions.append(f"What is the effect of voluntarily acquiring citizenship of a {c2}?")
                sub_questions.append(
                    f"Based on the constitutional provisions, what happens to {c1} when that condition occurs?"
                )
            elif "speaker" in c1.lower():
                sub_questions.append(f"What constitutional provision governs the role of the {c1} during a sitting?")
                sub_questions.append(f"What condition or event involving {c2} is described in the question?")
                sub_questions.append(
                    "When that condition occurs, what arrangement is made for the presiding officer?"
                )
            else:
                sub_questions.append(f"What legal rule applies to {c1}?")
                sub_questions.append(f"What condition or triggering event involving {c2} is described in the question?")
                sub_questions.append(
                    "Based on the constitutional provisions, what is the legal outcome when that condition occurs?"
                )

    # -------------------------------
    # ANALYTICAL
    # -------------------------------
    else:
        if len(articles) >= 2:
            for art in articles[:3]:
                hint = get_article_hint(art)
                if hint:
                    sub_questions.append(f"What does Article {art} provide regarding {hint}?")
                elif focus:
                    sub_questions.append(f"What does Article {art} provide regarding {focus}?")
                else:
                    sub_questions.append(f"What does Article {art} provide?")

            if focus and concepts:
                unique_concepts = []
                for c in concepts:
                    if c.lower() != focus.lower():
                        unique_concepts.append(c)

                if unique_concepts:
                    sub_questions.append(
                        f"How do these provisions together address {focus} in the context of {', '.join(unique_concepts)}?"
                    )
                else:
                    sub_questions.append(
                        f"How do these provisions together address {focus} in the original question?"
                    )
            else:
                sub_questions.append(
                    "How do these constitutional provisions work together to answer the original question?"
                )

        elif len(concepts) >= 2:
            c1 = concepts[0]
            c2 = concepts[1]

            # special case for fairness + public employment
            if "public employment" in [c.lower() for c in concepts] and focus == "fairness":
                sub_questions.append("What constitutional principle ensures equality in public employment?")
                sub_questions.append("What constitutional principle prohibits discrimination in public employment?")
                sub_questions.append("How do these constitutional principles together ensure fairness in public employment?")
            else:
                sub_questions.append(f"What constitutional principle or provision is related to {c1}?")
                sub_questions.append(f"What constitutional principle or provision is related to {c2}?")
                if len(concepts) >= 3:
                    sub_questions.append(f"What role does {concepts[2]} play in the constitutional context of the question?")
                sub_questions.append(
                    f"How do these principles or provisions collectively address {focus or 'the original question'}?"
                )

    # clean outputs
    sub_questions = [clean_text(sq) for sq in sub_questions]

    return {
        "question": question,
        "question_type": question_type,
        "articles_found": articles,
        "concepts_found": concepts,
        "focus": focus,
        "sub_questions": sub_questions
    }

test_questions = [
    "How do Articles 14 and 16(2) together ensure fairness in public employment?",
    "How does the duration of the Council of States differ from the duration of the House of the People?",
    "If a person voluntarily acquires the citizenship of a foreign State, what happens to their Indian citizenship?",
    "What happens if the Speaker is absent from a sitting?",
    "How is fairness in public employment protected?"
]

for q in test_questions:
    result = dataset_style_decompose_v3(q)
    print("\n====================================")
    print("Question:", result["question"])
    print("Type:", result["question_type"])
    print("Articles found:", result["articles_found"])
    print("Concepts found:", result["concepts_found"])
    print("Focus:", result["focus"])
    print("Generated sub-questions:")
    for i, sq in enumerate(result["sub_questions"], 1):
        print(f"{i}. {sq}")

def compare_with_ground_truth_v3(index):
    item = data[index]
    pred = dataset_style_decompose_v3(item["complex_question"], item["question_type"])

    print("\n========================================")
    print("COMPLEX QUESTION:", item["complex_question"])
    print("QUESTION TYPE:", item["question_type"])

    print("\nGROUND TRUTH:")
    for i, sq in enumerate(item["sub_questions"], 1):
        print(f"{i}. {sq['question']} [{sq['type']}]")

    print("\nPREDICTED:")
    for i, sq in enumerate(pred["sub_questions"], 1):
        print(f"{i}. {sq}")
    print("========================================")

compare_with_ground_truth_v3(6)
compare_with_ground_truth_v3(19)
compare_with_ground_truth_v3(24)

pred_rows = []

for item in data:
    pred = dataset_style_decompose_v3(item["complex_question"], item["question_type"])

    pred_rows.append({
        "id": item["id"],
        "question_type": item["question_type"],
        "complex_question": item["complex_question"],
        "ground_truth": " || ".join([sq["question"] for sq in item["sub_questions"]]),
        "predicted": " || ".join(pred["sub_questions"])
    })

pred_df = pd.DataFrame(pred_rows)
pred_df.head()

from difflib import SequenceMatcher

def similarity_score(a, b):
    return SequenceMatcher(None, a.lower(), b.lower()).ratio()

pred_df["similarity"] = pred_df.apply(
    lambda row: similarity_score(row["ground_truth"], row["predicted"]),
    axis=1
)

print("Average similarity:", pred_df["similarity"].mean())
print("\nBy question type:")
print(pred_df.groupby("question_type")["similarity"].mean())

"""# Generate T5 training files"""

import os

BASE_DIR = ".."   # because notebook is inside notebooks/
DATA_DIR = os.path.join(BASE_DIR, "data")
MODELS_DIR = os.path.join(BASE_DIR, "models")
OUTPUTS_DIR = os.path.join(BASE_DIR, "outputs")

t5_rows_v3 = []

for item in data:
    input_text = "decompose question: " + item["complex_question"]

    target_parts = []
    for i, sq in enumerate(item["sub_questions"], 1):
        target_parts.append(f"SUBQ{i}: {sq['question']}")

    target_text = " ".join(target_parts)

    t5_rows_v3.append({
        "id": item["id"],
        "question_type": item["question_type"],
        "input_text": input_text,
        "target_text": target_text
    })

t5_df_v3 = pd.DataFrame(t5_rows_v3)
print(t5_df_v3.head(3))

import pandas as pd
from datasets import Dataset

train_df = pd.read_csv("data/train_t5_v3.csv")
test_df = pd.read_csv("data/test_t5_v3.csv")

print(train_df.head(2))
print(test_df.head(2))

train_dataset = Dataset.from_pandas(train_df[["input_text", "target_text"]])
test_dataset = Dataset.from_pandas(test_df[["input_text", "target_text"]])

sample = train_df_v3.iloc[0]
print(sample["input_text"])
print()
print(sample["target_text"])

# pip install transformers datasets sentencepiece accelerate  (run manually if needed)

train_df = pd.read_csv("data/train_t5_v3.csv")
test_df = pd.read_csv("data/test_t5_v3.csv")

import pandas as pd
from datasets import Dataset
from transformers import (
    T5Tokenizer,
    T5ForConditionalGeneration,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq
)

model_name = "t5-small"

tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

max_input_length = 128
max_target_length = 256

def preprocess_function(examples):
    model_inputs = tokenizer(
        examples["input_text"],
        max_length=max_input_length,
        truncation=True,
        padding="max_length"
    )

    labels = tokenizer(
        text_target=examples["target_text"],
        max_length=max_target_length,
        truncation=True,
        padding="max_length"
    )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_train = train_dataset.map(preprocess_function, batched=True)
tokenized_test = test_dataset.map(preprocess_function, batched=True)

from transformers import T5ForConditionalGeneration

model = T5ForConditionalGeneration.from_pretrained("t5-small")

from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer, DataCollatorForSeq2Seq
import os

model_output_dir = "t5_decomposer_v4"
os.makedirs(model_output_dir, exist_ok=True)

training_args = Seq2SeqTrainingArguments(
    output_dir=model_output_dir,
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=3e-4,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=8,
    weight_decay=0.01,
    save_total_limit=2,
    predict_with_generate=True,
    logging_steps=20,
    fp16=False,
    report_to="none"
)

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    processing_class=tokenizer,
    data_collator=data_collator
)

trainer.train()

import re

def parse_subquestions_v3(output_text):
    parts = re.split(r"SUBQ\d+:|SUBq\d+:", output_text)
    return [p.strip() for p in parts if p.strip()]

import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

def generate_decomposition(question, model, tokenizer, max_length=256):
    input_text = "decompose question: " + question

    inputs = tokenizer(
        input_text,
        return_tensors="pt",
        truncation=True,
        max_length=128
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}

    output_ids = model.generate(
        **inputs,
        max_length=max_length,
        num_beams=5,
        early_stopping=True,
        no_repeat_ngram_size=3,
        repetition_penalty=2.0
    )

    return tokenizer.decode(output_ids[0], skip_special_tokens=True)

for q in test_questions:
    raw = generate_decomposition(q, model, tokenizer)
    parsed = parse_subquestions_v3(raw)

    print("\n====================================")
    print("QUESTION:", q)
    print("\nRAW OUTPUT:")
    print(raw)
    print("\nPARSED:")
    for i, sq in enumerate(parsed, 1):
        print(f"{i}. {sq}")

def compare_all_v3(index):
    item = data[index]

    question = item["complex_question"]
    ground_truth = [sq["question"] for sq in item["sub_questions"]]
    baseline_pred = dataset_style_decompose_v3(question, item["question_type"])["sub_questions"]

    t5_raw = generate_decomposition(question, model, tokenizer)
    t5_pred = parse_subquestions_v3(t5_raw)

    print("\n========================================")
    print("QUESTION:", question)
    print("TYPE:", item["question_type"])

    print("\nGROUND TRUTH:")
    for i, sq in enumerate(ground_truth, 1):
        print(f"{i}. {sq}")

    print("\nBASELINE:")
    for i, sq in enumerate(baseline_pred, 1):
        print(f"{i}. {sq}")

    print("\nT5 v3:")
    for i, sq in enumerate(t5_pred, 1):
        print(f"{i}. {sq}")

    print("========================================")

compare_all_v3(6)
compare_all_v3(19)
compare_all_v3(24)

from difflib import SequenceMatcher
import pandas as pd

def similarity_score(a, b):
    return SequenceMatcher(None, a.lower(), b.lower()).ratio()

results_v3 = []

for _, row in test_df.iterrows():
    question = row["input_text"].replace("decompose question: ", "")
    target = row["target_text"]

    pred_raw = generate_decomposition(question, model, tokenizer)
    pred_list = parse_subquestions_v3(pred_raw)
    pred_text = "\n".join(pred_list)

    results_v3.append({
        "question": question,
        "ground_truth": target,
        "prediction_raw": pred_raw,
        "prediction_parsed": pred_text,
        "similarity": similarity_score(target, pred_text)
    })

results_v3_df = pd.DataFrame(results_v3)

print("Average T5 v3 similarity:", results_v3_df["similarity"].mean())
print(results_v3_df.head(5))

baseline_results = []

for _, row in test_df.iterrows():
    question = row["input_text"].replace("decompose question: ", "")
    target = row["target_text"]

    baseline_pred = "\n".join(dataset_style_decompose_v3(question)["sub_questions"])

    baseline_results.append({
        "question": question,
        "ground_truth": target,
        "baseline_prediction": baseline_pred,
        "baseline_similarity": similarity_score(target, baseline_pred)
    })

baseline_results_df = pd.DataFrame(baseline_results)

print("Average Baseline similarity:", baseline_results_df["baseline_similarity"].mean())
print("Average T5 v3 similarity:", results_v3_df["similarity"].mean())

results_v3_df.to_csv("t5_v3_test_predictions.csv", index=False)
baseline_results_df.to_csv("baseline_test_predictions.csv", index=False)